### PR TITLE
Fix #132; use new API for credential verification

### LINKED ISSUE #132: TypeError: 'NoneType' object is not subscriptable
I get this exception when entering my credentials (manjaro, installed via yay -S nordnm)

[INFO] [nordnm.credentials]: Attempting to verify credentials...
Traceback (most recent call last):
  File "/usr/bin/nordnm", line 11, in <module>
    load_entry_point('nordnm==0.6.1', 'console_scripts', 'nordnm')()
  File "/usr/lib/python3.7/site-packages/nordnm/__main__.py", line 26, in main
    nordnm.NordNM()
  File "/usr/lib/python3.7/site-packages/nordnm/nordnm.py", line 202, in __init__
    self.setup()
  File "/usr/lib/python3.7/site-packages/nordnm/nordnm.py", line 315, in setup
    self.credentials = CredentialsHandler(paths.CREDENTIALS)
  File "/usr/lib/python3.7/site-packages/nordnm/credentials.py", line 21, in __init__
    self.save_new_credentials()  # Prompt for credentials
  File "/usr/lib/python3.7/site-packages/nordnm/credentials.py", line 68, in save_new_credentials
    if nordapi.verify_user_credentials(username, password):
  File "/usr/lib/python3.7/site-packages/nordnm/nordapi.py", line 99, in verify_user_credentials
    return validate_user_token(token_json, password)
  File "/usr/lib/python3.7/site-packages/nordnm/nordapi.py", line 80, in validate_user_token
    token = token_json['token']
TypeError: 'NoneType' object is not subscriptable

### PR DESCRIPTION
**Pull request by evs-ch**
My python-fu is somewhat weak, I hope I didn't commit any large sins in there :)

### CODE REVIEW

**Comment by Chadsr** [comment]
LGTM, Thanks for the contribution.

Merging and will do some brief testing when I acquire a NordVPN account again.

**Comment by Chadsr** [comment]
Oh, just noticed that the response isn't checked for a 200 (OK) status code. I will add that in myself since I've already merged.

**Comment by evs-ch** [comment]
I didn't keep it in because the docs said the response object evaluates to true if the code is between 200 and 400 – but explicitly checking for something in the 200 range probably makes more sense, I guess. 

The API returns a 401 and a bit of JSON, btw, when you provide invalid credentials (just in case you might need it somewhere ^^)
```json
{"errors":{"code":101301,"message":"Unauthorized"}}
```

It also returns a 201 when successful, so looking at your recent commit you'd probably have to check for everything in the 200 range or explicitly check for 201 (maybe via `requests.codes.created` ?) [there](https://github.com/Chadsr/NordVPN-NetworkManager/blob/a62c2791f3729272b6c62b09c05d0841a9301fc3/nordnm/nordapi.py#L85).

**Comment by Chadsr** [comment]
Ah, good point. I do however rather to check for specific codes for clarity. As you pointed out I did however jump to conclusions that it would be 200, without testing the API... Will change that to a 201 ASAP, or use a dict of 20x codes, indeed.

Thanks again for your time. I have very little of it to spare at the moment. :)

**Comment by evs-ch** [comment]
Awesome :)

Just did a quick check, seems to work as it should.

Yeah, time's always at a premium somehow… so I'm truly sorry for throwing two more PRs at you in a few minutes ;)

**Pull request merged**
